darknet_ros:
  ros__parameters:
    yolo_model:

      config_file:
        name: yolov3-tiny.cfg
      weight_file:
        name: yolov3-tiny.backup
      threshold:
        value: 0.6
      detection_classes:
        names:
          - cone
