darknet_ros:
  ros__parameters:
    yolo_model:

      config_file:
        name: yolov3-tiny.cfg
      weight_file:
        name: yolov3-tiny_30000.weights
      threshold:
        value: 0.3
      detection_classes:
        names:
          - cone

