darknet_ros:
  ros__parameters:
    yolo_model:

      config_file:
        name: yolov3.cfg
      weight_file:
        name: yolov3_20000.weights
      threshold:
        value: 0.4
      detection_classes:
        names:
          - cone
